# Generated by Django 3.1.4 on 2021-01-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('total_result', models.IntegerField(default=0)),
                ('Sent_result', models.CharField(max_length=1000)),
            ],
        ),
    ]
