# Generated by Django 3.1.4 on 2021-01-07 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runrnn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Sent_result',
            field=models.CharField(max_length=1000, validators=[django.core.validators.int_list_validator]),
        ),
    ]
