# Generated by Django 3.1.4 on 2021-01-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runrnn', '0002_auto_20210107_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='Sent_result',
            new_name='sent_result',
        ),
    ]
